= Hardware specifications

Where did your run your tests? A laptop, or goldengate?
I ran my tests on my laptop through the terminal on VSCode.

What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)

    Performance Specifications of the Machine:

CPU Architecture: x86_64 (supports 32-bit and 64-bit)
Total Logical Processors (Threads): 8
Physical Cores: 4 (2 threads per core)
Socket: 1
Model: 11th Gen Intel(R) Core(TM) i7-1165G7
Base Clock Speed: 2.80 GHz

Total RAM: 7784 MB (about 7.8 GB)

= Single-process mandelbrot

Run your executable, `single_mandelbrot`, with the following sizes and record
the amount of time it takes to compute each image.

[cols="1,1"]
!===
| Size | Time (s) 
| 100 | 0.474974 
| 400 | 7.067308
| 800 | 32.805023
| 1000 | 69.686188
| 2000 | 238.066895 
!===

= Multi-process mandelbrot

Run your executable, `multi_mandelbrot`, with the following sizes and record
the amount of time it takes to compute each image.

[cols="1,1"]
!===
| Size | Time (s) 
| 100 | 0.503426
| 400 | 9.107046
| 800 | 34.571430
| 1000 | 51.442127 
| 2000 | 219.643890
!===
